# -*- coding: utf-8 -*-
"""Team3_MotionGPT3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jV6pl5T8DYre9uCkrzxcq4EfiWtdfcD-

# 🏃 MotionGPT — Full Demo Notebook
### Human Motion as a Foreign Language (NeurIPS 2023)

| Task | Description |
|------|-------------|
| 📝 **Text → Motion** | Generate 3D skeleton animation from text |
| 🎬 **Motion → Text** | Caption a motion sequence |
| 🔵 **In-Between** | Fill masked middle frames |
| 🟠 **Prediction** | Predict future from a motion prefix |

> ⚡ **Before running:** `Runtime → Change runtime type → T4 GPU`

## 🔧 Step 1 — Environment Setup
"""

# Check GPU
import subprocess
r = subprocess.run(['nvidia-smi'], capture_output=True, text=True)
print(r.stdout if r.returncode == 0 else '⚠️  No GPU! Go to Runtime → Change runtime type → T4 GPU')

# Commented out IPython magic to ensure Python compatibility.
# Clone MotionGPT repo
import os
REPO = '/content/MotionGPT'
if not os.path.exists(REPO):
    !git clone https://github.com/OpenMotionLab/MotionGPT.git {REPO}
    print('Cloned.')
else:
    print('Already cloned.')
# %cd {REPO}
print('CWD:', os.getcwd())

# Install compatible packages for current Colab (PyTorch 2.2+, Python 3.10+)
# Step 1: Core ML stack — use whatever torch Colab already has
import torch
print(f'Colab torch version: {torch.__version__}')
print(f'CUDA available: {torch.cuda.is_available()}')

# Install MotionGPT dependencies compatible with Colab 2024/2025
!pip install -q pytorch-lightning==2.2.5
!pip install -q 'transformers>=4.36.0,<4.42.0'
!pip install -q 'tokenizers>=0.15.0'
!pip install -q omegaconf einops rich tqdm
!pip install -q moviepy==1.0.3 imageio imageio-ffmpeg
!pip install -q matplotlib
!pip install -q 'gradio>=3.50.0,<4.0.0'
!pip install -q gdown
!pip install -q scipy
# Spacy for linguistic metrics
!python -m spacy download en_core_web_sm -q
print('\n✅  All packages installed.')

# IMPORTANT: Restart runtime after installs, then re-run from Step 2
# This ensures all packages are loaded correctly.
import os
print('⚠️  If this is your first run, click: Runtime → Restart runtime')
print('Then run ALL cells again from the top (Ctrl+F9).')
print('If already restarted, continue to Step 2.')

"""## 📦 Step 2 — Download Models & Dependencies"""

# Commented out IPython magic to ensure Python compatibility.
import os
# %cd /content/MotionGPT

# 2.1 Pretrained MotionGPT checkpoint
CKPT = 'checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar'
os.makedirs('checkpoints/MotionGPT-base', exist_ok=True)

if not os.path.exists(CKPT):
    print('Downloading MotionGPT-base checkpoint from HuggingFace...')
    !git lfs install -q
    # Clone without LFS blobs first (fast), then pull only the checkpoint
    !GIT_LFS_SKIP_SMUDGE=1 git clone https://huggingface.co/OpenMotionLab/MotionGPT-base checkpoints/MotionGPT-base 2>/dev/null || true
    !cd checkpoints/MotionGPT-base && git lfs pull --include='motiongpt_s3_h3d.tar'
    print(f'✅  Checkpoint downloaded: {os.path.exists(CKPT)}')
else:
    print(f'✅  Checkpoint already exists')

# Commented out IPython magic to ensure Python compatibility.
# 2.2 SMPL body model
import os
# %cd /content/MotionGPT

if not os.path.exists('deps/smpl'):
    os.makedirs('deps', exist_ok=True)
#     %cd deps
    !gdown 'https://drive.google.com/uc?id=1qrFkPZyRwRGd0Q3EY76K8oJaIgs_WK9i'
    !tar xfzv smpl.tar.gz && rm smpl.tar.gz
#     %cd /content/MotionGPT
    print('✅  SMPL model downloaded')
else:
    print('✅  SMPL already exists')

# Commented out IPython magic to ensure Python compatibility.
# 2.3 Flan-T5-base language model
import os
# %cd /content/MotionGPT

if not os.path.exists('deps/flan-t5-base'):
#     %cd deps
    !git lfs install -q
    !git clone https://huggingface.co/google/flan-t5-base
#     %cd /content/MotionGPT
    print('✅  Flan-T5 downloaded')
else:
    print('✅  Flan-T5 already exists')

# Commented out IPython magic to ensure Python compatibility.
# 2.4 T2M evaluators (mean/std stats for HumanML3D)
import os
# %cd /content/MotionGPT

if not os.path.exists('deps/t2m'):
#     %cd deps
    !gdown 'https://drive.google.com/uc?id=1AYsmEG8I3fAAoraT4vau0GnesWBWyeT8'
    !tar xfzv t2m.tar.gz && rm t2m.tar.gz
#     %cd /content/MotionGPT
    print('✅  T2M evaluators downloaded')
else:
    print('✅  T2M evaluators already exist')

# Commented out IPython magic to ensure Python compatibility.
import os
# %cd /content/MotionGPT/deps

# The tar extracted as smpl_models/ but code expects smpl/
!mv smpl_models smpl

# %cd /content/MotionGPT
print('SMPL exists:', os.path.exists('deps/smpl'))
print('Contents:', os.listdir('deps/smpl'))

# Commented out IPython magic to ensure Python compatibility.
import os
# %cd /content/MotionGPT/deps

# Try gdown first
!gdown 'https://drive.google.com/uc?id=1qrFkPZyRwRGd0Q3EY76K8oJaIgs_WK9i'

# If that fails, try with --fuzzy flag
# !gdown --fuzzy 'https://drive.google.com/file/d/1qrFkPZyRwRGd0Q3EY76K8oJaIgs_WK9i'

!tar xfzv smpl.tar.gz && rm smpl.tar.gz
# %cd /content/MotionGPT
print('Exists:', os.path.exists('deps/smpl'))

# 2.5 Verify all required files exist
import os
checks = [
    ('Checkpoint',     'checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar'),
    ('SMPL model',     'deps/smpl'),
    ('Flan-T5',        'deps/flan-t5-base'),
    ('T2M evaluators', 'deps/t2m'),
]
all_ok = True
for name, path in checks:
    ok = os.path.exists(path)
    print(f'  {"✅" if ok else "❌"} {name}: {path}')
    if not ok: all_ok = False
print('\n✅  All dependencies ready!' if all_ok else '\n❌  Some files missing — re-run above cells.')

"""## 🔑 Step 3 — Load MotionGPT Model
Run this once. All tasks below reuse the loaded model.
"""

# Commented out IPython magic to ensure Python compatibility.
import os, sys, time
import numpy as np
import torch
from pathlib import Path
from IPython.display import HTML, display
from base64 import b64encode

# %cd /content/MotionGPT
if '/content/MotionGPT' not in sys.path:
    sys.path.insert(0, '/content/MotionGPT')

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Device: {DEVICE}')
print(f'Torch:  {torch.__version__}')

# Patch pytorch-lightning compatibility (pl 2.x renamed some APIs)
import pytorch_lightning as pl
print(f'PyTorch Lightning: {pl.__version__}')

# The repo was written for pl 1.x; patch seed_everything location if needed
try:
    from pytorch_lightning import seed_everything
except ImportError:
    from lightning_fabric.utilities.seed import seed_everything
    pl.seed_everything = seed_everything

print('✅  PyTorch Lightning patched for compatibility')

# Commented out IPython magic to ensure Python compatibility.
import os
# %cd /content/MotionGPT/deps

# Check what actually extracted
print(os.listdir('t2m'))

# Commented out IPython magic to ensure Python compatibility.
import os
# %cd /content/MotionGPT/deps

# Check full structure
for root, dirs, files in os.walk('t2m'):
    level = root.replace('t2m', '').count(os.sep)
    indent = ' ' * 2 * level
    print(f'{indent}{root}/')
    for f in files[:3]:  # show first 3 files per folder
        print(f'{indent}  {f}')

# Commented out IPython magic to ensure Python compatibility.
import os, shutil
# %cd /content/MotionGPT/deps

# Fix t2m: move t2m/t2m/ contents up to t2m/
src_t2m = 't2m/t2m'
if os.path.exists(src_t2m):
    for item in os.listdir(src_t2m):
        src = f'{src_t2m}/{item}'
        dst = f't2m/{item}'
        if not os.path.exists(dst):
            shutil.move(src, dst)
    shutil.rmtree(src_t2m)
    print('✅  Fixed t2m nesting')

# Fix glove: move t2m/glove/glove/ contents up to glove/
src_glove = 't2m/glove/glove'
if os.path.exists(src_glove):
    os.makedirs('glove', exist_ok=True)
    for item in os.listdir(src_glove):
        src = f'{src_glove}/{item}'
        dst = f'glove/{item}'
        if not os.path.exists(dst):
            shutil.move(src, dst)
    shutil.rmtree('t2m/glove')
    print('✅  Fixed glove nesting')

# Verify
expected = '/content/MotionGPT/deps/t2m/VQVAEV3_CB1024_CMT_H1024_NRES3/meta/mean.npy'
print('mean.npy exists:', os.path.exists(expected))
print('glove exists:   ', os.path.exists('/content/MotionGPT/deps/glove/our_vab_idx.pkl'))

# %cd /content/MotionGPT

# Commented out IPython magic to ensure Python compatibility.
import os, shutil
# %cd /content/MotionGPT/deps

# Check what's now directly inside t2m/
print('t2m/ contents:', os.listdir('t2m'))

# There's likely still a t2m/ inside t2m/ — fix it
src = 't2m/t2m'
if os.path.exists(src):
    for item in os.listdir(src):
        s = f'{src}/{item}'
        d = f't2m/{item}'
        if not os.path.exists(d):
            shutil.move(s, d)
    shutil.rmtree(src)
    print('✅  Fixed second level')

# Verify
expected = 'deps/t2m/VQVAEV3_CB1024_CMT_H1024_NRES3/meta/mean.npy'
print('mean.npy exists:', os.path.exists(f'/content/MotionGPT/{expected}'))
print('t2m/ contents now:', os.listdir('t2m'))

# Commented out IPython magic to ensure Python compatibility.
import os, shutil
# %cd /content/MotionGPT/deps

# Re-download and extract fresh, then manually place correctly
!gdown '1AYsmEG8I3fAAoraT4vau0GnesWBWyeT8' -O t2m_fresh.tar.gz

import tarfile
with tarfile.open('t2m_fresh.tar.gz') as tar:
    tar.extractall('t2m_raw')

# Show full structure to find where t2m evaluator lives
for root, dirs, files in os.walk('t2m_raw'):
    for f in files:
        if 'mean.npy' in f:
            print(os.path.join(root, f))

from omegaconf import OmegaConf
# Patch: allow re-registering the eval resolver on kernel restarts
if OmegaConf.has_resolver("eval"):
    OmegaConf.clear_resolvers()

# Patch the source file to use replace=True
import re

fpath = '/content/MotionGPT/mGPT/config.py'
with open(fpath, 'r') as f:
    src = f.read()

src = src.replace(
    'OmegaConf.register_new_resolver("eval", eval)',
    'OmegaConf.register_new_resolver("eval", eval, replace=True)'
)

with open(fpath, 'w') as f:
    f.write(src)

print('Patched config.py')

import os
os.makedirs('/content/MotionGPT/deps/configs', exist_ok=True)
!cp /content/MotionGPT/configs/assets.yaml /content/MotionGPT/deps/configs/assets.yaml
print('Copied. Exists:', os.path.exists('/content/MotionGPT/deps/configs/assets.yaml'))

# Commented out IPython magic to ensure Python compatibility.
import os
# %cd /content/MotionGPT
print('CWD:', os.getcwd())

# Then re-run the load cell

# Commented out IPython magic to ensure Python compatibility.
import os, shutil, tarfile
# %cd /content/MotionGPT/deps

# Re-download and extract properly
!gdown '1AYsmEG8I3fAAoraT4vau0GnesWBWyeT8' -O t2m_fresh.tar.gz

with tarfile.open('t2m_fresh.tar.gz') as tar:
    tar.extractall('t2m_raw', filter='data')

# The correct contents are at t2m_raw/t2m/t2m/
src = 't2m_raw/t2m/t2m'
if os.path.exists('t2m'):
    shutil.rmtree('t2m')
shutil.copytree(src, 't2m')

# Cleanup
shutil.rmtree('t2m_raw')
os.remove('t2m_fresh.tar.gz')

print('mean.npy exists:', os.path.exists('t2m/VQVAEV3_CB1024_CMT_H1024_NRES3/meta/mean.npy'))
print('t2m contents:', [x for x in os.listdir('t2m') if not x.startswith('.')])
# %cd /content/MotionGPT

# Commented out IPython magic to ensure Python compatibility.
import os, shutil
# %cd /content/MotionGPT/deps

# Move t2m/t2m/ contents up into t2m/
src = 't2m/t2m'
for item in os.listdir(src):
    s = f'{src}/{item}'
    d = f't2m/{item}'
    if not os.path.exists(d):
        shutil.move(s, d)
shutil.rmtree(src)

print('mean.npy exists:', os.path.exists('t2m/VQVAEV3_CB1024_CMT_H1024_NRES3/meta/mean.npy'))
print('t2m contents:', [x for x in os.listdir('t2m') if not x.startswith('.')])
# %cd /content/MotionGPT

# Commented out IPython magic to ensure Python compatibility.
import os
# %cd /content/MotionGPT

# Create minimal dummy dataset structure to pass initialization
os.makedirs('datasets/humanml3d/new_joint_vecs', exist_ok=True)
os.makedirs('datasets/humanml3d/texts', exist_ok=True)
os.makedirs('datasets/humanml3d/new_joints', exist_ok=True)

# Download the split files from the repo
!wget -q https://raw.githubusercontent.com/EricGuo5513/HumanML3D/main/HumanML3D/test.txt -O datasets/humanml3d/test.txt
!wget -q https://raw.githubusercontent.com/EricGuo5513/HumanML3D/main/HumanML3D/train.txt -O datasets/humanml3d/train.txt
!wget -q https://raw.githubusercontent.com/EricGuo5513/HumanML3D/main/HumanML3D/val.txt -O datasets/humanml3d/val.txt
!wget -q https://raw.githubusercontent.com/EricGuo5513/HumanML3D/main/HumanML3D/train_val.txt -O datasets/humanml3d/train_val.txt

print('Split files:')
for f in ['test.txt','train.txt','val.txt']:
    path = f'datasets/humanml3d/{f}'
    if os.path.exists(path):
        lines = open(path).readlines()
        print(f'  ✅ {f}: {len(lines)} entries')
    else:
        print(f'  ❌ {f} missing')

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
# %cd /content/MotionGPT

# Read first 10 IDs from test.txt (tiny=True only loads a few)
with open('datasets/humanml3d/test.txt') as f:
    ids = [line.strip() for line in f.readlines()[:20]]

# Create dummy motion npy files (shape T x 263, HumanML3D feature dim)
os.makedirs('datasets/humanml3d/new_joint_vecs', exist_ok=True)
os.makedirs('datasets/humanml3d/new_joints', exist_ok=True)
os.makedirs('datasets/humanml3d/texts', exist_ok=True)

for mid in ids:
    # Dummy motion features: 60 frames x 263 dims
    npy_path = f'datasets/humanml3d/new_joint_vecs/{mid}.npy'
    if not os.path.exists(npy_path):
        np.save(npy_path, np.zeros((60, 263), dtype=np.float32))

    # Dummy joints: 60 frames x 22 joints x 3 dims
    jnt_path = f'datasets/humanml3d/new_joints/{mid}.npy'
    if not os.path.exists(jnt_path):
        np.save(jnt_path, np.zeros((60, 22, 3), dtype=np.float32))

    # Dummy text annotation
    txt_path = f'datasets/humanml3d/texts/{mid}.txt'
    if not os.path.exists(txt_path):
        with open(txt_path, 'w') as f:
            f.write('a person walks forward#walk/NN\n')

print(f'Created dummy files for {len(ids)} motion IDs')
print('Example:', os.listdir('datasets/humanml3d/new_joint_vecs')[:3])

# Check what min/max lengths the dataset expects
import subprocess
result = subprocess.run(['grep', '-n', 'min_motion\|max_motion\|length_list\|new_name_list',
                        '/content/MotionGPT/mGPT/data/humanml/dataset_t2m.py'],
                       capture_output=True, text=True)
print(result.stdout[:3000])

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
# %cd /content/MotionGPT

# Recreate dummy files with correct length (100 frames) and proper text format
with open('datasets/humanml3d/test.txt') as f:
    ids = [line.strip() for line in f.readlines()[:20]]

for mid in ids:
    # Motion: 100 frames x 263 dims (well above min_motion_length=40)
    np.save(f'datasets/humanml3d/new_joint_vecs/{mid}.npy',
            np.random.randn(100, 263).astype(np.float32))
    np.save(f'datasets/humanml3d/new_joints/{mid}.npy',
            np.random.randn(100, 22, 3).astype(np.float32))

    # Text format must be: "caption#tokens#start#end" per line
    with open(f'datasets/humanml3d/texts/{mid}.txt', 'w') as f:
        f.write('a person walks forward#walk/NN walk/VB#0.0#10.0\n')

print(f'Recreated {len(ids)} dummy files with 100 frames and correct text format')

# Verify one file
sample = ids[0]
print(f'\nSample {sample}:')
print(f'  motion shape: {np.load(f"datasets/humanml3d/new_joint_vecs/{sample}.npy").shape}')
print(f'  text: {open(f"datasets/humanml3d/texts/{sample}.txt").read().strip()}')

!pip install -q bert-score

# Commented out IPython magic to ensure Python compatibility.
import os, sys, time
import numpy as np
import torch
from pathlib import Path
from IPython.display import HTML, display
from base64 import b64encode

# %cd /content/MotionGPT
if '/content/MotionGPT' not in sys.path:
    sys.path.insert(0, '/content/MotionGPT')

to_remove = [k for k in sys.modules if 'mGPT' in k]
for k in to_remove:
    del sys.modules[k]

from omegaconf import OmegaConf
OmegaConf.clear_resolvers()

from mGPT.config import parse_args
from mGPT.data.build_data import build_data
from mGPT.models.build_model import build_model
import mGPT.render.matplot.plot_3d_global as plot_3d

sys.argv = ['notebook', '--cfg', 'configs/config_h3d_stage3.yaml', '--task', 't2m', '--example', 'demos/t2m.txt']

cfg = parse_args(phase='demo')
cfg.FOLDER                          = 'results'
cfg.TEST.CHECKPOINTS                = 'checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar'
cfg.DATASET.TRANSFORM_PATH          = 'deps/transforms/'
cfg.DATASET.WORD_VERTILIZER_PATH    = 'deps/glove/'
cfg.DATASET.HUMANML3D.MEAN_STD_PATH = 'deps/'
cfg.DATASET.KIT.MEAN_STD_PATH       = 'deps/'
cfg.METRIC.TM2T.t2m_path            = 'deps/'

import pytorch_lightning as pl
pl.seed_everything(cfg.SEED_VALUE)
Path(cfg.FOLDER).mkdir(parents=True, exist_ok=True)

print('Building datamodule...')
datamodule = build_data(cfg)
print('Building model...')
model = build_model(cfg, datamodule)
print('Loading checkpoint...')
ckpt = torch.load(cfg.TEST.CHECKPOINTS, map_location='cpu')
model.load_state_dict(ckpt['state_dict'])
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(DEVICE)
model.eval()
print(f'\n✅  Model loaded | device: {DEVICE}')

"""## 🛠️ Step 4 — Utility Functions"""

# ── Token helpers ────────────────────────────────────────────────────────
def motion_token_to_string(motion_token, lengths, codebook_size=512):
    out = []
    for i in range(motion_token.shape[0]):
        tokens = motion_token[i].cpu().tolist()[:lengths[i]]
        out.append(
            f'<motion_id_{codebook_size}>' +
            ''.join(f'<motion_id_{int(t)}>' for t in tokens) +
            f'<motion_id_{codebook_size+1}>'
        )
    return out

# ── GIF renderer ─────────────────────────────────────────────────────────────
def render_gif(joints_np, title='motion'):
    """Render (T,J,3) joint array to an animated GIF and return the path."""
    out_dir = Path('/content/MotionGPT/results'); out_dir.mkdir(exist_ok=True)
    path = str(out_dir / f'{title}_{int(time.time())}.gif')
    if joints_np.ndim == 3: joints_np = joints_np[None]   # add batch dim
    plot_3d.draw_to_batch(joints_np, [title], [path])
    return path

# ── Inline GIF display ───────────────────────────────────────────────────────
def show_gif(path, title=''):
    with open(path, 'rb') as f:
        b64 = b64encode(f.read()).decode()
    display(HTML(
        f'<p><b>{title}</b></p>'
        f'<img src="data:image/gif;base64,{b64}" style="max-width:480px;border:1px solid #ccc;border-radius:8px"/>'
    ))

# ── Load + encode a .npy motion file ────────────────────────────────────────
def encode_motion_file(npy_path):
    """Load HumanML3D feature .npy, normalize, encode to tokens. Returns dict."""
    feats = torch.tensor(np.load(npy_path), device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]          # (1, T, 263)
    feats = model.datamodule.normalize(feats)
    with torch.no_grad():
        motion_token, _ = model.vae.encode(feats)
    tok_str = motion_token_to_string(motion_token, [motion_token.shape[1]])[0]
    joints  = model.feats2joints(feats).cpu().numpy()[0]   # (T, J, 3)
    return dict(
        feats=feats,
        motion_token=motion_token,
        motion_token_string=tok_str,
        motion_token_length=motion_token.shape[1],
        joints=joints,
        length=feats.shape[1],
    )

print('✅  Utilities ready.')

"""---
## 🟢 Task 1 — Text → Motion
Edit `TEXT_PROMPT` and run the cells below.

**Example prompts:**
- `"a person waves their right hand and bows"`
- `"someone jogs forward and then jumps"`
- `"a person kicks with the right leg then walks backward"`
"""

# ✏️  Edit your prompt here
TEXT_PROMPT   = 'a person waves their right hand and then bows'
TARGET_LENGTH = 0   # frames; 0 = model decides

with torch.no_grad():
    outputs_t2m = model(
        {'length': [TARGET_LENGTH], 'text': [TEXT_PROMPT]},
        task='t2m'
    )

out_feats   = outputs_t2m['feats'][0]
out_length  = outputs_t2m['length'][0]
out_joints  = outputs_t2m['joints'][:out_length].detach().cpu().numpy()
out_texts   = outputs_t2m['texts'][0]

print(f'Prompt : {TEXT_PROMPT}')
print(f'Frames : {out_length}  ({out_length/20:.1f}s @ 20fps)')
print(f'Echo   : {out_texts[:120]}')

gif_t2m = render_gif(out_joints, title='t2m')
show_gif(gif_t2m, f'T2M — "{TEXT_PROMPT}"')

# Save joint positions for re-use in Tasks 2-4
np.save('results/t2m_joints.npy', out_joints)
print(f'Joints saved → results/t2m_joints.npy  shape={out_joints.shape}')

# ── Batch mode: run all 7 paper-style prompts ───────────────────────────
BATCH_PROMPTS = [
    'a person takes hurried steps forward without raising their arms',
    'a person lifts both hands above their head then lowers them slowly',
    'someone walks to the right, turns around, and walks back to the left',
    'a person squats down using mainly their right leg then stands back up',
    'a man waves his hands from side to side',
    'someone jogs forward and then jumps high',
    'a person kicks with the right leg then walks backward three steps',
]

print('Running batch T2M generation...\n')
with torch.no_grad():
    for i, prompt in enumerate(BATCH_PROMPTS):
        out = model({'length': [0], 'text': [prompt]}, task='t2m')
        j   = out['joints'][:out['length'][0]].detach().cpu().numpy()
        g   = render_gif(j, f't2m_batch_{i}')
        show_gif(g, f'[{i+1}/{len(BATCH_PROMPTS)}] {prompt}')
        print(f'  [{i+1}] {out["length"][0]} frames')

"""---
## 🟡 Task 2 — Motion → Text
Caption the motion generated in Task 1, or upload your own `.npy`.
"""

def ui_m2t(f):
    if f is None: return '⚠️  Upload a .npy file.'

    data = np.load(f.name)
    print(f'Uploaded shape: {data.shape}')

    # Must be (T, 263) — if it's joints format, we can't directly use it
    if data.ndim == 3 or (data.ndim == 2 and data.shape[-1] != 263):
        return f'⚠️  Expected shape (T, 263), got {data.shape}. Please upload a HumanML3D feature .npy file.'

    feats = torch.tensor(data, device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]
    feats = model.datamodule.normalize(feats)

    with torch.no_grad():
        tok, _ = model.vae.encode(feats)

    tok_str = motion_token_to_string(tok, [tok.shape[1]])[0]
    inst    = 'Describe the motion illustrated in <motion> using text.'
    prompt  = model.lm.placeholder_fulfill(inst, feats.shape[1], tok_str, '')

    with torch.no_grad():
        out = model({'length': [feats.shape[1]], 'text': [prompt]}, task='m2t')

    return '📝 ' + out['texts'][0]

# Save a proper test file from the T2M output (correct 263-dim format)
import numpy as np
np.save('/content/test_motion.npy', out_feats.cpu().numpy())
print('Saved test_motion.npy — upload this to the M2T tab')

from google.colab import files
files.download('/content/test_motion.npy')

def ui_m2t(f):
    if f is None: return '⚠️  Upload a .npy file.'

    data = np.load(f.name)
    feats = torch.tensor(data, device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]
    # Don't normalize — file is already from model output

    with torch.no_grad():
        tok, _ = model.vae.encode(feats)

    tlen    = tok.shape[1]
    cs      = model.hparams.codebook_size
    tok_str = motion_token_to_string(tok, [tlen])[0]

    # Build prompt with token string directly (bypass placeholder_fulfill)
    prompt = f'Describe the motion illustrated in {tok_str} using text.'

    with torch.no_grad():
        out = model({'length': [feats.shape[1]], 'text': [prompt]}, task='m2t')

    result = out['texts'][0]
    return '📝 ' + result

# Rebuild Gradio with fixed M2T
demo.close()

# Caption the T2M output from Task 1
feats_m2t = out_feats.unsqueeze(0) if out_feats.ndim == 2 else out_feats

with torch.no_grad():
    tok_m2t, _ = model.vae.encode(feats_m2t)

tok_str_m2t = motion_token_to_string(tok_m2t, [tok_m2t.shape[1]])[0]

inst_m2t   = 'Describe the motion illustrated in <motion> using text.'
prompt_m2t = model.lm.placeholder_fulfill(inst_m2t, out_length, tok_str_m2t, '')

with torch.no_grad():
    out_m2t = model({'length': [out_length], 'text': [prompt_m2t]}, task='m2t')

caption = out_m2t['texts'][0]
print('─' * 60)
print(f'Original prompt : "{TEXT_PROMPT}"')
print(f'M2T caption     : "{caption}"')
print('─' * 60)
show_gif(gif_t2m, f'M2T Caption: "{caption}"')

# Optional: upload a custom .npy and get a caption
# ─────────────────────────────────────────────────
# from google.colab import files
# uploaded = files.upload()
# npy_path = list(uploaded.keys())[0]
#
# md_data = encode_motion_file(npy_path)
# inst    = 'Describe the motion illustrated in <motion> using text.'
# prompt  = model.lm.placeholder_fulfill(inst, md_data['length'], md_data['motion_token_string'], '')
# with torch.no_grad():
#     out = model({'length': [md_data['length']], 'text': [prompt]}, task='m2t')
# print('Caption:', out['texts'][0])
# show_gif(render_gif(md_data['joints'], 'm2t_custom'), out['texts'][0])
print('Uncomment the block above to caption a custom .npy file.')

def motion_token_to_string(motion_token, lengths, codebook_size=512):
    out = []
    for i in range(motion_token.shape[0]):
        tokens = motion_token[i].cpu().tolist()[:lengths[i]]
        out.append(
            f'<motion_id_{codebook_size}>' +
            ''.join(f'<motion_id_{int(t)}>' for t in tokens) +
            f'<motion_id_{codebook_size+1}>'
        )
    return out

def render_gif(joints_np, title='motion'):
    out_dir = Path('/content/MotionGPT/results'); out_dir.mkdir(exist_ok=True)
    path = str(out_dir / f'{title}_{int(time.time())}.gif')
    if joints_np.ndim == 3: joints_np = joints_np[None]
    plot_3d.draw_to_batch(joints_np, [title], [path])
    return path

def show_gif(path, title=''):
    with open(path, 'rb') as f:
        b64 = b64encode(f.read()).decode()
    display(HTML(
        f'<p><b>{title}</b></p>'
        f'<img src="data:image/gif;base64,{b64}" style="max-width:480px"/>'
    ))

def encode_motion_file(npy_path):
    feats = torch.tensor(np.load(npy_path), device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]
    feats = model.datamodule.normalize(feats)
    with torch.no_grad():
        motion_token, _ = model.vae.encode(feats)
    tok_str = motion_token_to_string(motion_token, [motion_token.shape[1]])[0]
    joints  = model.feats2joints(feats).cpu().numpy()[0]
    return dict(feats=feats, motion_token=motion_token,
                motion_token_string=tok_str,
                motion_token_length=motion_token.shape[1],
                joints=joints, length=feats.shape[1])

# Set codebook size from model
CS = model.hparams.codebook_size
print(f'✅  Utilities ready. Codebook size: {CS}')

TEXT_PROMPT = 'a person waves their right hand and then bows'
TARGET_LENGTH = 0

with torch.no_grad():
    outputs_t2m = model(
        {'length': [TARGET_LENGTH], 'text': [TEXT_PROMPT]},
        task='t2m'
    )

out_feats  = outputs_t2m['feats'][0]
out_length = outputs_t2m['length'][0]
out_joints = outputs_t2m['joints'][:out_length].detach().cpu().numpy()
out_texts  = outputs_t2m['texts'][0]

print(f'Prompt : {TEXT_PROMPT}')
print(f'Frames : {out_length}  ({out_length/20:.1f}s @ 20fps)')
print(f'Echo   : {out_texts[:120]}')

gif_t2m = render_gif(out_joints, title='t2m')
show_gif(gif_t2m, f'T2M — "{TEXT_PROMPT}"')

feats_m2t = out_feats.unsqueeze(0) if out_feats.ndim == 2 else out_feats

with torch.no_grad():
    tok_m2t, _ = model.vae.encode(feats_m2t)

tok_str_m2t = motion_token_to_string(tok_m2t, [tok_m2t.shape[1]])[0]
inst_m2t    = 'Describe the motion illustrated in <motion> using text.'
prompt_m2t  = model.lm.placeholder_fulfill(inst_m2t, out_length, tok_str_m2t, '')

with torch.no_grad():
    out_m2t = model({'length': [out_length], 'text': [prompt_m2t]}, task='m2t')

caption = out_m2t['texts'][0]
print('─' * 60)
print(f'Original prompt : "{TEXT_PROMPT}"')
print(f'M2T caption     : "{caption}"')
print('─' * 60)
show_gif(gif_t2m, f'M2T Caption: "{caption}"')

"""---
## 🔵 Task 3 — Motion In-Between
The model fills in the masked middle 50% of a motion sequence.
"""

feats_ib = (out_feats.unsqueeze(0) if out_feats.ndim == 2 else out_feats).to(DEVICE)
joints   = out_joints.squeeze(0) if out_joints.ndim == 4 else out_joints

with torch.no_grad():
    tok_ib, _ = model.vae.encode(feats_ib)

tlen   = tok_ib.shape[1]
cs     = model.hparams.codebook_size
s2, s3 = tlen // 4, tlen // 4 * 3
tlist  = tok_ib[0].tolist()

masked_str = (
    f'<motion_id_{cs}>' +
    ''.join(f'<motion_id_{int(t)}>' for t in tlist[:s2]) +
    f'<motion_id_{cs+2}>' * (s3 - s2) +
    ''.join(f'<motion_id_{int(t)}>' for t in tlist[s3:]) +
    f'<motion_id_{cs+1}>'
)
prompt_ib = f'Complete the masked motion: {masked_str}'

heading = feats_ib[0, :feats_ib.shape[1] // 4]
tailing = feats_ib[0, feats_ib.shape[1] // 4 * 3:]

with torch.no_grad():
    out_ib = model({
        'length':         [0],
        'text':           [prompt_ib],
        'motion_heading': [heading],
        'motion_tailing': [tailing],
    }, task='inbetween')

ib_len    = out_ib['length'][0]
ib_joints = out_ib['joints'][:ib_len].detach().cpu().numpy()
if ib_joints.ndim == 4: ib_joints = ib_joints.squeeze(0)
gif_ib = render_gif(ib_joints, 'ib_output')

masked_joints = np.concatenate([
    joints[:int(out_length * 0.25)],
    np.zeros((int(out_length * 0.50), joints.shape[1], 3)),
    joints[int(out_length * 0.75):]
])
gif_masked = render_gif(masked_joints, 'ib_masked')

print(f'Output frames: {ib_len}')
show_gif(gif_t2m,    '✅ Original Full Motion')
show_gif(gif_masked, '⬛ Masked Input')
show_gif(gif_ib,     '🔵 In-Between Result')



"""---
## 🟠 Task 4 — Motion Prediction
Given the first 20% of a motion, predict the remaining frames.
"""

feats_pred = (out_feats.unsqueeze(0) if out_feats.ndim == 2 else out_feats).to(DEVICE)
joints     = out_joints.squeeze(0) if out_joints.ndim == 4 else out_joints

with torch.no_grad():
    tok_pred, _ = model.vae.encode(feats_pred)

prefix_len  = max(1, tok_pred.shape[1] // 5)
prefix_head = tok_pred[:, :prefix_len]
cs          = model.hparams.codebook_size

prefix_str = (
    f'<motion_id_{cs}>' +
    ''.join(f'<motion_id_{int(t)}>' for t in tok_pred[0, :prefix_len].tolist()) +
    f'<motion_id_{cs+1}>'
)
prompt_pred = f'Predict the future motion given the prefix motion: {prefix_str}'

with torch.no_grad():
    pf = model.vae.decode(prefix_head)
    prefix_joints = model.feats2joints(pf).cpu().numpy()[0]
if prefix_joints.ndim == 4: prefix_joints = prefix_joints.squeeze(0)

gif_prefix = render_gif(prefix_joints, 'pred_prefix')
show_gif(gif_prefix, f'🟠 Prefix Input — first {prefix_len} tokens')

with torch.no_grad():
    out_pred = model({
        'length': [0],
        'text':   [prompt_pred],
        'motion': [prefix_head[0]],  # raw token tensor
    }, task='pred')

print('length:', out_pred['length'])
print('texts:',  out_pred['texts'])

if out_pred['length']:
    pred_len    = out_pred['length'][0]
    pred_joints = out_pred['joints'][:pred_len].detach().cpu().numpy()
    if pred_joints.ndim == 4: pred_joints = pred_joints.squeeze(0)
    gif_pred = render_gif(pred_joints, 'pred_output')
    print(f'Predicted frames: {pred_len}')
    show_gif(gif_prefix, '🟠 Prefix Input (first 20%)')
    show_gif(gif_pred,   '🟠 Predicted Future Motion')
    show_gif(gif_t2m,    '🟢 Ground-Truth Full Motion (reference)')
else:
    print('No motion generated. Text output:', out_pred['texts'])

with open('/content/MotionGPT/mGPT/models/mgpt.py') as f:
    lines = f.readlines()
for i, line in enumerate(lines[70:120], start=71):
    print(f'{i}: {line}', end='')

# Patch mgpt.py to fix pred task lengths
fpath = '/content/MotionGPT/mGPT/models/mgpt.py'
with open(fpath) as f:
    src = f.read()

old = '''            if task == "pred":
                motion = self.vae.decode(
                    torch.cat((batch["motion"][i], outputs[i])))
            elif task in ["t2m", "m2t", "inbetween"]:
                motion = self.vae.decode(outputs[i])
                # motion = self.datamodule.denormalize(motion)
                lengths.append(motion.shape[1])'''

new = '''            if task == "pred":
                motion = self.vae.decode(
                    torch.cat((batch["motion"][i], outputs[i])))
                lengths.append(motion.shape[1])
            elif task in ["t2m", "m2t", "inbetween"]:
                motion = self.vae.decode(outputs[i])
                # motion = self.datamodule.denormalize(motion)
                lengths.append(motion.shape[1])'''

src = src.replace(old, new)
with open(fpath, 'w') as f:
    f.write(src)
print('Patched mgpt.py')

# Commented out IPython magic to ensure Python compatibility.
import os, sys, time
import numpy as np
import torch
from pathlib import Path
from IPython.display import HTML, display
from base64 import b64encode

# %cd /content/MotionGPT
if '/content/MotionGPT' not in sys.path:
    sys.path.insert(0, '/content/MotionGPT')

to_remove = [k for k in sys.modules if 'mGPT' in k]
for k in to_remove:
    del sys.modules[k]

from omegaconf import OmegaConf
OmegaConf.clear_resolvers()

from mGPT.config import parse_args
from mGPT.data.build_data import build_data
from mGPT.models.build_model import build_model
import mGPT.render.matplot.plot_3d_global as plot_3d

sys.argv = ['notebook', '--cfg', 'configs/config_h3d_stage3.yaml', '--task', 't2m', '--example', 'demos/t2m.txt']

cfg = parse_args(phase='demo')
cfg.FOLDER                          = 'results'
cfg.TEST.CHECKPOINTS                = 'checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar'
cfg.DATASET.TRANSFORM_PATH          = 'deps/transforms/'
cfg.DATASET.WORD_VERTILIZER_PATH    = 'deps/glove/'
cfg.DATASET.HUMANML3D.MEAN_STD_PATH = 'deps/'
cfg.DATASET.KIT.MEAN_STD_PATH       = 'deps/'
cfg.METRIC.TM2T.t2m_path            = 'deps/'

import pytorch_lightning as pl
pl.seed_everything(cfg.SEED_VALUE)
Path(cfg.FOLDER).mkdir(parents=True, exist_ok=True)

print('Building datamodule...')
datamodule = build_data(cfg)
print('Building model...')
model = build_model(cfg, datamodule)
print('Loading checkpoint...')
ckpt = torch.load(cfg.TEST.CHECKPOINTS, map_location='cpu')
model.load_state_dict(ckpt['state_dict'])
DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model.to(DEVICE)
model.eval()
print(f'\n✅  Model loaded | device: {DEVICE}')

# Read the pred forward logic
with open('/content/MotionGPT/mGPT/models/mgpt.py') as f:
    src = f.read()
# Show lines around pred task
lines = src.split('\n')
for i, line in enumerate(lines):
    if 'pred' in line.lower() or 'motion_head' in line.lower():
        print(f'{i}: {line}')

# Check how demo.py handles pred task
r = open('/content/MotionGPT/demos/pred.txt').read()
print(r)

print('out_pred keys:', out_pred.keys())
print('length:', out_pred['length'])
print('texts:', out_pred['texts'])

import subprocess
r = subprocess.run(['grep', '-n', 'pred\|motion_head\|prefix',
                   '/content/MotionGPT/mGPT/models/mgpt.py'],
                  capture_output=True, text=True)
print(r.stdout[:3000])

# Utilities
CS = model.hparams.codebook_size

def motion_token_to_string(motion_token, lengths, codebook_size=512):
    out = []
    for i in range(motion_token.shape[0]):
        tokens = motion_token[i].cpu().tolist()[:lengths[i]]
        out.append(
            f'<motion_id_{codebook_size}>' +
            ''.join(f'<motion_id_{int(t)}>' for t in tokens) +
            f'<motion_id_{codebook_size+1}>'
        )
    return out

def render_gif(joints_np, title='motion'):
    out_dir = Path('/content/MotionGPT/results'); out_dir.mkdir(exist_ok=True)
    path = str(out_dir / f'{title}_{int(time.time())}.gif')
    if joints_np.ndim == 3: joints_np = joints_np[None]
    plot_3d.draw_to_batch(joints_np, [title], [path])
    return path

def show_gif(path, title=''):
    with open(path, 'rb') as f:
        b64 = b64encode(f.read()).decode()
    display(HTML(f'<p><b>{title}</b></p><img src="data:image/gif;base64,{b64}" style="max-width:480px"/>'))

print(f'✅  Utilities ready. CS={CS}')

feats_pred = (out_feats.unsqueeze(0) if out_feats.ndim == 2 else out_feats).to(DEVICE)
joints     = out_joints.squeeze(0) if out_joints.ndim == 4 else out_joints

with torch.no_grad():
    tok_pred, _ = model.vae.encode(feats_pred)

tlen       = tok_pred.shape[1]
cs         = model.hparams.codebook_size
prefix_len = max(1, tlen // 5)
token_list = tok_pred[0].tolist()

motion_split1 = (
    f'<motion_id_{cs}>' +
    ''.join(f'<motion_id_{int(t)}>' for t in token_list[:prefix_len]) +
    f'<motion_id_{cs+1}>'
)
prompt_pred = f'Predict motion: {motion_split1}'

with torch.no_grad():
    pf = model.vae.decode(tok_pred[:, :prefix_len])
    prefix_joints = model.feats2joints(pf).cpu().numpy()[0]
if prefix_joints.ndim == 4: prefix_joints = prefix_joints.squeeze(0)

gif_prefix = render_gif(prefix_joints, 'pred_prefix')
show_gif(gif_prefix, f'🟠 Prefix Input — first {prefix_len} tokens')

with torch.no_grad():
    out_pred = model({
        'length': [0],
        'text':   [prompt_pred],
        'motion': [tok_pred[0, :prefix_len]],
    }, task='pred')

print('length:', out_pred['length'])
print('texts:',  out_pred['texts'])

if out_pred['length']:
    pred_len    = out_pred['length'][0]
    pred_joints = out_pred['joints'][:pred_len].detach().cpu().numpy()
    if pred_joints.ndim == 4: pred_joints = pred_joints.squeeze(0)
    gif_pred = render_gif(pred_joints, 'pred_output')
    print(f'Predicted frames: {pred_len}')
    show_gif(gif_prefix, '🟠 Prefix Input (first 20%)')
    show_gif(gif_pred,   '🟠 Predicted Future Motion')
    show_gif(gif_t2m,    '🟢 Ground-Truth Full Motion (reference)')
else:
    print('No motion generated. Text:', out_pred['texts'])

# Run prediction inference
with torch.no_grad():
    out_pred = model(
        {'length': [out_length], 'text': [prompt_pred], 'motion': [prefix_head[0]]},
        task='pred'
    )

pred_joints = out_pred['joints'][:out_pred['length'][0]].detach().cpu().numpy()
gif_pred    = render_gif(pred_joints, 'pred_output')

print(f'Predicted frames: {out_pred["length"][0]}')
show_gif(gif_prefix, '🟠 Prefix Input (first 20%)')
show_gif(gif_pred,   '🟠 Predicted Future')
show_gif(gif_t2m,    '🟢 Ground-Truth Full Motion (reference)')

"""---
## 🎛️ Step 5 — Interactive Gradio App
All four tasks in one web UI. A public shareable link will appear below.
"""

# Speed up generation settings
model.lm.language_model.config.num_beams = 1
model.lm.language_model.config.do_sample = False
model.lm.language_model.config.max_new_tokens = 200

print('✅  Fast mode enabled')
print(f'num_beams: {model.lm.language_model.config.num_beams}')
print(f'do_sample: {model.lm.language_model.config.do_sample}')

import time

TEXT_PROMPT = 'a person waves their right hand'
TARGET_LENGTH = 60  # 3 seconds — much faster than 196 frames

start = time.time()

with torch.no_grad():
    outputs_t2m = model(
        {'length': [TARGET_LENGTH], 'text': [TEXT_PROMPT]},
        task='t2m'
    )

elapsed = time.time() - start

out_feats  = outputs_t2m['feats'][0]
out_length = outputs_t2m['length'][0]
out_joints = outputs_t2m['joints'][:out_length].detach().cpu().numpy()

print(f'⚡ Generated in {elapsed:.1f}s  |  {out_length} frames ({out_length/20:.1f}s of motion)')

gif_t2m = render_gif(out_joints, 'fast_t2m')
show_gif(gif_t2m, TEXT_PROMPT)

print(type(model.lm))
print([x for x in dir(model.lm) if not x.startswith('_')])

method = "fast"   # remove dropdown completely

def render_motion(data, feats, method='fast'):
    fname = str(np.random.randint(10000))
    gif_path = os.path.join(output_dir, fname + ".gif")

    if len(data.shape) == 3:
        data = data[None]

    if isinstance(data, torch.Tensor):
        data = data.cpu().numpy()

    # 🔥 Reduce resolution
    data = data[:, :, :] * 0.5

    plot_3d.draw_to_batch(data, [''], [gif_path])

    return gif_path, fname + ".gif", None, None

chatbot = gr.Chatbot(height=350)

import gradio as gr

def ui_t2m(text, tlen):
    if not text.strip(): return None, '⚠️  Enter a text prompt.'
    with torch.no_grad():
        out = model({'length': [int(tlen)], 'text': [text]}, task='t2m')
    j = out['joints'][:out['length'][0]].detach().cpu().numpy()
    if j.ndim == 4: j = j.squeeze(0)
    return render_gif(j, 'ui_t2m'), f'✅ {out["length"][0]} frames'

def ui_m2t(f):
    if f is None: return '⚠️  Upload a .npy file.'
    data  = np.load(f.name)
    feats = torch.tensor(data, device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]
    with torch.no_grad():
        tok, _ = model.vae.encode(feats)
    cs      = model.hparams.codebook_size
    tok_str = motion_token_to_string(tok, [tok.shape[1]])[0]
    prompt  = f'Describe the motion illustrated in {tok_str} using text.'
    with torch.no_grad():
        out = model({'length': [feats.shape[1]], 'text': [prompt]}, task='m2t')
    return '📝 ' + out['texts'][0]

def ui_inbetween(f):
    if f is None: return None, None, '⚠️  Upload a .npy file.'
    data  = np.load(f.name)
    feats = torch.tensor(data, device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]
    with torch.no_grad():
        tok, _ = model.vae.encode(feats)
    tl = tok.shape[1]; cs = model.hparams.codebook_size
    s2, s3 = tl//4, tl//4*3; tlist = tok[0].tolist()
    mstr = (f'<motion_id_{cs}>' +
            ''.join(f'<motion_id_{int(t)}>' for t in tlist[:s2]) +
            f'<motion_id_{cs+2}>'*(s3-s2) +
            ''.join(f'<motion_id_{int(t)}>' for t in tlist[s3:]) +
            f'<motion_id_{cs+1}>')
    heading = feats[0, :feats.shape[1]//4]
    tailing = feats[0, feats.shape[1]//4*3:]
    with torch.no_grad():
        out = model({'length': [0], 'text': [f'Complete the masked motion: {mstr}'],
                     'motion_heading': [heading], 'motion_tailing': [tailing]}, task='inbetween')
    j = out['joints'][:out['length'][0]].detach().cpu().numpy()
    if j.ndim == 4: j = j.squeeze(0)
    jin = model.feats2joints(feats).cpu().numpy()[0]
    if jin.ndim == 4: jin = jin.squeeze(0)
    return render_gif(jin, 'ui_ib_in'), render_gif(j, 'ui_ib_out'), f'✅ {out["length"][0]} frames'

def ui_pred(f):
    if f is None: return None, None, '⚠️  Upload a .npy file.'
    data  = np.load(f.name)
    feats = torch.tensor(data, device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]
    with torch.no_grad():
        tok, _ = model.vae.encode(feats)
    plen = max(1, tok.shape[1]//5); cs = model.hparams.codebook_size
    pstr = (f'<motion_id_{cs}>' +
            ''.join(f'<motion_id_{int(t)}>' for t in tok[0,:plen].tolist()) +
            f'<motion_id_{cs+1}>')
    with torch.no_grad():
        out = model({'length': [0], 'text': [f'Predict motion: {pstr}'],
                     'motion': [tok[0,:plen]]}, task='pred')
    pj = out['joints'][:out['length'][0]].detach().cpu().numpy()
    if pj.ndim == 4: pj = pj.squeeze(0)
    pfj = model.feats2joints(model.vae.decode(tok[:,:plen])).cpu().numpy()[0]
    if pfj.ndim == 4: pfj = pfj.squeeze(0)
    return render_gif(pfj, 'ui_pred_in'), render_gif(pj, 'ui_pred_out'), f'✅ {out["length"][0]} frames'

with gr.Blocks(title='MotionGPT Demo', theme=gr.themes.Soft()) as demo:
    gr.Markdown('# 🏃 MotionGPT Demo  ·  T2M · M2T · In-Between · Prediction')

    with gr.Tab('📝 Text → Motion'):
        t_prompt = gr.Textbox(label='Action description',
                              placeholder='a person waves their right hand and bows', lines=2)
        t_len    = gr.Slider(0, 300, value=0, step=10, label='Target length (0=auto)')
        t_btn    = gr.Button('Generate 🎬', variant='primary')
        t_gif    = gr.Image(label='Result', type='filepath')
        t_inf    = gr.Textbox(label='Info', interactive=False)
        t_btn.click(ui_t2m, [t_prompt, t_len], [t_gif, t_inf])
        gr.Examples([
            ['a person waves their right hand and bows'],
            ['someone jogs forward and jumps'],
            ['a person kicks with the right leg then walks backward'],
            ['a man squats down and stands up quickly'],
        ], t_prompt)

    with gr.Tab('🎬 Motion → Text'):
        gr.Markdown('Upload `test_motion.npy` (saved from T2M output) or any HumanML3D feature file.')
        m_file = gr.File(label='Upload .npy', file_types=['.npy'])
        m_btn  = gr.Button('Caption 📝', variant='primary')
        m_out  = gr.Textbox(label='Caption', lines=3, interactive=False)
        m_btn.click(ui_m2t, [m_file], [m_out])

    with gr.Tab('🔵 In-Between'):
        ib_file = gr.File(label='Upload .npy', file_types=['.npy'])
        ib_btn  = gr.Button('Complete 🔵', variant='primary')
        with gr.Row():
            ib_in  = gr.Image(label='Original',  type='filepath')
            ib_out = gr.Image(label='Completed', type='filepath')
        ib_inf = gr.Textbox(label='Info', interactive=False)
        ib_btn.click(ui_inbetween, [ib_file], [ib_in, ib_out, ib_inf])

    with gr.Tab('🟠 Prediction'):
        pd_file = gr.File(label='Upload .npy', file_types=['.npy'])
        pd_btn  = gr.Button('Predict 🟠', variant='primary')
        with gr.Row():
            pd_in  = gr.Image(label='Prefix',    type='filepath')
            pd_out = gr.Image(label='Predicted', type='filepath')
        pd_inf = gr.Textbox(label='Info', interactive=False)
        pd_btn.click(ui_pred, [pd_file], [pd_in, pd_out, pd_inf])

demo.launch(share=True, debug=False)

with gr.Blocks(title='MotionGPT Demo', theme=gr.themes.Soft()) as demo:
    gr.Markdown('# 🏃 MotionGPT Demo  ·  T2M · M2T · In-Between · Prediction')

    with gr.Tab('📝 Text → Motion'):
        gr.Markdown('Type any action description and generate a 3D skeleton animation.')
        with gr.Row():
            t_prompt = gr.Textbox(label='Action description',
                                  placeholder='a person waves their right hand and bows', lines=2)
            t_len    = gr.Slider(0, 300, value=0, step=10,
                                 label='Target length in frames (0 = auto)')
        t_btn = gr.Button('🎬 Generate Motion', variant='primary')
        t_gif = gr.Image(label='Generated Animation', type='filepath')
        t_inf = gr.Textbox(label='Info', interactive=False)
        t_btn.click(ui_t2m, [t_prompt, t_len], [t_gif, t_inf])
        gr.Examples([
            ['a person waves their right hand and then bows'],
            ['someone jogs forward and then jumps high'],
            ['a person kicks with the right leg then walks backward'],
            ['a man squats down and stands up quickly'],
            ['a person walks in a circle and then stops'],
            ['someone picks up an object with both hands and places it down'],
        ], t_prompt)

    with gr.Tab('🎬 Motion → Text'):
        gr.Markdown('Upload a HumanML3D `.npy` motion feature file to get a caption.')
        m_file = gr.File(label='Upload .npy motion file', file_types=['.npy'])
        m_btn  = gr.Button('📝 Generate Caption', variant='primary')
        m_out  = gr.Textbox(label='Generated Caption', lines=3, interactive=False)
        m_btn.click(ui_m2t, [m_file], [m_out])

    with gr.Tab('🔵 In-Between'):
        gr.Markdown('Upload `.npy` → model fills in the missing middle 50% of motion.')
        ib_file = gr.File(label='Upload .npy motion file', file_types=['.npy'])
        ib_btn  = gr.Button('🔵 Complete Motion', variant='primary')
        with gr.Row():
            ib_gif_in  = gr.Image(label='Original Input',     type='filepath')
            ib_gif_out = gr.Image(label='Completed Motion',   type='filepath')
        ib_info = gr.Textbox(label='Info', interactive=False)
        ib_btn.click(ui_inbetween, [ib_file], [ib_gif_in, ib_gif_out, ib_info])

    with gr.Tab('🟠 Prediction'):
        gr.Markdown('Upload `.npy` → predict future frames from the first 20% of motion.')
        pd_file = gr.File(label='Upload .npy motion file', file_types=['.npy'])
        pd_btn  = gr.Button('🟠 Predict Future', variant='primary')
        with gr.Row():
            pd_gif_in  = gr.Image(label='Prefix Input (20%)', type='filepath')
            pd_gif_out = gr.Image(label='Predicted Future',   type='filepath')
        pd_info = gr.Textbox(label='Info', interactive=False)
        pd_btn.click(ui_pred, [pd_file], [pd_gif_in, pd_gif_out, pd_info])

    with gr.Tab('ℹ️ About'):
        gr.Markdown("""
        ## MotionGPT Model Details
        | Property | Value |
        |---|---|
        | Base LM | Flan-T5-base |
        | Motion tokenizer | VQ-VAE (codebook 512) |
        | Training dataset | HumanML3D |
        | Conference | NeurIPS 2023 |

        **Motion .npy format:** `(T, 263)` HumanML3D feature vectors.
        Sample motions available in the [HumanML3D repo](https://github.com/EricGuo5513/HumanML3D).

        **Links:** [Paper](https://arxiv.org/abs/2306.14795) · [GitHub](https://github.com/OpenMotionLab/MotionGPT) · [HuggingFace](https://huggingface.co/OpenMotionLab)
        """)

demo.launch(share=True, debug=False)

"""---
## 📊 Step 6 — Quantitative Evaluation (Optional)
Requires the HumanML3D dataset. Follow the [setup guide](https://github.com/EricGuo5513/HumanML3D).
"""

!pip install -q huggingface_hub
from huggingface_hub import login, HfApi
login()  # paste your HF token from https://huggingface.co/settings/tokens

# Mount Google Drive if your dataset is stored there
# from google.colab import drive
# drive.mount('/content/drive')
# !ln -s /content/drive/MyDrive/humanml3d datasets/humanml3d

# Run evaluation (uncomment the task you want)
# !python -m test --cfg configs/config_h3d_stage3.yaml --task t2m       --nodebug
# !python -m test --cfg configs/config_h3d_stage3.yaml --task m2t       --nodebug
# !python -m test --cfg configs/config_h3d_stage3.yaml --task inbetween --nodebug
# !python -m test --cfg configs/config_h3d_stage3.yaml --task pred      --nodebug
print('Uncomment the commands above after linking your HumanML3D dataset.')

from huggingface_hub import HfApi
api = HfApi()

HF_USERNAME = 'GopiBharath'
SPACE_NAME  = 'Motion_GPT3'
REPO_ID     = f'{HF_USERNAME}/{SPACE_NAME}'

print(f'Using existing space: https://huggingface.co/spaces/{REPO_ID}')

"""---
## 💾 Step 7 — Download All Results
"""

from huggingface_hub import login
login()  # this will show a prompt to paste your token interactively

from huggingface_hub import HfApi
import shutil, os

api = HfApi()

HF_USERNAME = 'GopiBharath'
SPACE_NAME  = 'Motion_GPT3'
REPO_ID     = f'{HF_USERNAME}/{SPACE_NAME}'

# 1. Upload app files
for fname in ['app.py', 'requirements.txt', 'README.md']:
    api.upload_file(
        path_or_fileobj=f'/content/hf_space/{fname}',
        path_in_repo=fname,
        repo_id=REPO_ID,
        repo_type='space',
    )
    print(f'✅  {fname} uploaded')

# 2. Upload checkpoint
print('Uploading checkpoint (~500MB)...')
api.upload_file(
    path_or_fileobj='/content/MotionGPT/checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar',
    path_in_repo='checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar',
    repo_id=REPO_ID,
    repo_type='space',
)
print('✅  Checkpoint uploaded')

# 3. Zip and upload MotionGPT source
print('Zipping source...')
shutil.make_archive('/content/motiongpt_src', 'zip', '/content/MotionGPT')
api.upload_file(
    path_or_fileobj='/content/motiongpt_src.zip',
    path_in_repo='motiongpt_src.zip',
    repo_id=REPO_ID,
    repo_type='space',
)
print('✅  Source uploaded')

# 4. Upload deps folder
print('Uploading deps (~2GB, takes a few minutes)...')
api.upload_folder(
    folder_path='/content/MotionGPT/deps',
    path_in_repo='deps',
    repo_id=REPO_ID,
    repo_type='space',
)
print('✅  Deps uploaded')

# 5. Upload datasets folder
print('Uploading datasets...')
api.upload_folder(
    folder_path='/content/MotionGPT/datasets',
    path_in_repo='datasets',
    repo_id=REPO_ID,
    repo_type='space',
)
print('✅  Datasets uploaded')

print(f'\n🎉  All uploaded! Space: https://huggingface.co/spaces/{REPO_ID}')
print('Space will take 10-15 min to build. Monitor at:')
print(f'https://huggingface.co/spaces/{REPO_ID} → Logs tab')

# Delete the large files we accidentally uploaded to the Space
from huggingface_hub import HfApi
api = HfApi()
REPO_ID = 'GopiBharath/Motion_GPT3'

# List all files in the space
files = api.list_repo_files(repo_id=REPO_ID, repo_type='space')
for f in files:
    print(f)

# Delete any large files that were partially uploaded
from huggingface_hub import HfApi
api = HfApi()

files_to_delete = [
    'checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar',
    'motiongpt_src.zip',
]

for f in files_to_delete:
    try:
        api.delete_file(
            path_in_repo=f,
            repo_id='GopiBharath/Motion_GPT3',
            repo_type='space',
        )
        print(f'✅  Deleted {f}')
    except Exception as e:
        print(f'⚠️  {f}: {e}')

from huggingface_hub import HfApi
api = HfApi()
REPO_ID = 'GopiBharath/Motion_GPT3'

# Check what's currently in the space
files = list(api.list_repo_files(repo_id=REPO_ID, repo_type='space'))
print('Current files in space:')
for f in files:
    print(f'  {f}')

# Update README to use ZeroGPU
readme = """---
title: MotionGPT Demo
emoji: 🏃
colorFrom: blue
colorTo: purple
sdk: gradio
sdk_version: 3.50.2
app_file: app.py
pinned: false
license: mit
hardware: zero-gpu
---

# 🏃 MotionGPT Demo
**Human Motion as a Foreign Language** (NeurIPS 2023)

Supports 4 tasks:
- 📝 Text → Motion
- 🎬 Motion → Text
- 🔵 In-Between
- 🟠 Prediction
"""

with open('/content/hf_space/README.md', 'w') as f:
    f.write(readme)

# Upload all 3 files
for fname in ['app.py', 'requirements.txt', 'README.md']:
    api.upload_file(
        path_or_fileobj=f'/content/hf_space/{fname}',
        path_in_repo=fname,
        repo_id=REPO_ID,
        repo_type='space',
    )
    print(f'✅  {fname} uploaded')

print(f'\n🚀  Space: https://huggingface.co/spaces/{REPO_ID}')
print('Building now — check Logs tab in ~2 min')

import os
os.makedirs('/content/hf_space', exist_ok=True)

# ── requirements.txt ──────────────────────────────────────────────────────
reqs = """torch==2.2.0
pytorch-lightning==2.2.5
transformers>=4.36.0
tokenizers>=0.15.0
omegaconf
einops
rich
tqdm
scipy
moviepy==1.0.3
imageio
imageio-ffmpeg
matplotlib
gradio>=3.50.0,<4.0.0
bert-score
spacy
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl
"""
with open('/content/hf_space/requirements.txt', 'w') as f:
    f.write(reqs)

# ── README.md ─────────────────────────────────────────────────────────────
readme = """---
title: MotionGPT Demo
emoji: 🏃
colorFrom: blue
colorTo: purple
sdk: gradio
sdk_version: 3.50.2
app_file: app.py
pinned: false
license: mit
hardware: t4-small
---

# MotionGPT Demo
Human Motion as a Foreign Language (NeurIPS 2023)

Supports: Text→Motion · Motion→Text · In-Between · Prediction
"""
with open('/content/hf_space/README.md', 'w') as f:
    f.write(readme)

# ── app.py ────────────────────────────────────────────────────────────────
app_code = """
import subprocess, os, sys, time
import numpy as np
import torch
from pathlib import Path
import gradio as gr

# Unzip source if needed
if not os.path.exists("/home/user/app/mGPT"):
    print("Extracting MotionGPT source...")
    subprocess.run(["unzip", "-q", "motiongpt_src.zip", "-d", "/home/user/app/"], check=True)

sys.path.insert(0, "/home/user/app")
os.chdir("/home/user/app")

from omegaconf import OmegaConf
OmegaConf.clear_resolvers()
from mGPT.config import parse_args
from mGPT.data.build_data import build_data
from mGPT.models.build_model import build_model
import mGPT.render.matplot.plot_3d_global as plot_3d

sys.argv = ["app", "--cfg", "configs/config_h3d_stage3.yaml",
            "--task", "t2m", "--example", "demos/t2m.txt"]

cfg = parse_args(phase="demo")
cfg.FOLDER                          = "/tmp/results"
cfg.TEST.CHECKPOINTS                = "checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar"
cfg.DATASET.TRANSFORM_PATH          = "deps/transforms/"
cfg.DATASET.WORD_VERTILIZER_PATH    = "deps/glove/"
cfg.DATASET.HUMANML3D.MEAN_STD_PATH = "deps/"
cfg.DATASET.KIT.MEAN_STD_PATH       = "deps/"
cfg.METRIC.TM2T.t2m_path            = "deps/"

import pytorch_lightning as pl
pl.seed_everything(cfg.SEED_VALUE)
Path("/tmp/results").mkdir(parents=True, exist_ok=True)

datamodule = build_data(cfg)
model      = build_model(cfg, datamodule)
ckpt       = torch.load(cfg.TEST.CHECKPOINTS, map_location="cpu")
model.load_state_dict(ckpt["state_dict"])
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(DEVICE)
model.eval()

model.lm.language_model.config.num_beams     = 1
model.lm.language_model.config.do_sample     = False
model.lm.language_model.config.max_new_tokens = 200
print(f"Model ready on {DEVICE}")

def motion_token_to_string(motion_token, lengths, codebook_size=512):
    out = []
    for i in range(motion_token.shape[0]):
        tokens = motion_token[i].cpu().tolist()[:lengths[i]]
        out.append(
            f"<motion_id_{codebook_size}>" +
            "".join(f"<motion_id_{int(t)}>" for t in tokens) +
            f"<motion_id_{codebook_size+1}>"
        )
    return out

def render_gif(joints_np, title="motion"):
    out_dir = Path("/tmp/results"); out_dir.mkdir(exist_ok=True)
    path = str(out_dir / f"{title}_{int(time.time())}.gif")
    if joints_np.ndim == 3: joints_np = joints_np[None]
    plot_3d.draw_to_batch(joints_np, [title], [path])
    return path

def ui_t2m(text, tlen):
    if not text.strip(): return None, "Enter a text prompt."
    with torch.no_grad():
        out = model({"length": [int(tlen)], "text": [text]}, task="t2m")
    j = out["joints"][:out["length"][0]].detach().cpu().numpy()
    if j.ndim == 4: j = j.squeeze(0)
    return render_gif(j, "ui_t2m"), f"{out['length'][0]} frames"

def ui_m2t(f):
    if f is None: return "Upload a .npy file."
    data  = np.load(f.name)
    feats = torch.tensor(data, device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]
    with torch.no_grad():
        tok, _ = model.vae.encode(feats)
    cs      = model.hparams.codebook_size
    tok_str = motion_token_to_string(tok, [tok.shape[1]])[0]
    prompt  = f"Describe the motion illustrated in {tok_str} using text."
    with torch.no_grad():
        out = model({"length": [feats.shape[1]], "text": [prompt]}, task="m2t")
    return out["texts"][0]

def ui_inbetween(f):
    if f is None: return None, None, "Upload a .npy file."
    data  = np.load(f.name)
    feats = torch.tensor(data, device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]
    with torch.no_grad():
        tok, _ = model.vae.encode(feats)
    tl = tok.shape[1]; cs = model.hparams.codebook_size
    s2, s3 = tl//4, tl//4*3; tlist = tok[0].tolist()
    mstr = (f"<motion_id_{cs}>" +
            "".join(f"<motion_id_{int(t)}>" for t in tlist[:s2]) +
            f"<motion_id_{cs+2}>"*(s3-s2) +
            "".join(f"<motion_id_{int(t)}>" for t in tlist[s3:]) +
            f"<motion_id_{cs+1}>")
    heading = feats[0, :feats.shape[1]//4]
    tailing = feats[0, feats.shape[1]//4*3:]
    with torch.no_grad():
        out = model({"length": [0],
                     "text": [f"Complete the masked motion: {mstr}"],
                     "motion_heading": [heading],
                     "motion_tailing": [tailing]}, task="inbetween")
    j = out["joints"][:out["length"][0]].detach().cpu().numpy()
    if j.ndim == 4: j = j.squeeze(0)
    jin = model.feats2joints(feats).cpu().numpy()[0]
    if jin.ndim == 4: jin = jin.squeeze(0)
    return render_gif(jin, "ui_ib_in"), render_gif(j, "ui_ib_out"), f"{out['length'][0]} frames"

def ui_pred(f):
    if f is None: return None, None, "Upload a .npy file."
    data  = np.load(f.name)
    feats = torch.tensor(data, device=DEVICE).float()
    if feats.ndim == 2: feats = feats[None]
    with torch.no_grad():
        tok, _ = model.vae.encode(feats)
    plen = max(1, tok.shape[1]//5); cs = model.hparams.codebook_size
    pstr = (f"<motion_id_{cs}>" +
            "".join(f"<motion_id_{int(t)}>" for t in tok[0,:plen].tolist()) +
            f"<motion_id_{cs+1}>")
    with torch.no_grad():
        out = model({"length": [0],
                     "text": [f"Predict motion: {pstr}"],
                     "motion": [tok[0,:plen]]}, task="pred")
    pj = out["joints"][:out["length"][0]].detach().cpu().numpy()
    if pj.ndim == 4: pj = pj.squeeze(0)
    pfj = model.feats2joints(model.vae.decode(tok[:,:plen])).cpu().numpy()[0]
    if pfj.ndim == 4: pfj = pfj.squeeze(0)
    return render_gif(pfj, "ui_pred_in"), render_gif(pj, "ui_pred_out"), f"{out['length'][0]} frames"

with gr.Blocks(title="MotionGPT Demo", theme=gr.themes.Soft()) as demo:
    gr.Markdown("# 🏃 MotionGPT Demo  · T2M · M2T · In-Between · Prediction")
    with gr.Tab("📝 Text → Motion"):
        t_prompt = gr.Textbox(label="Action description",
                              placeholder="a person waves their right hand", lines=2)
        t_len    = gr.Slider(0, 300, value=60, step=10, label="Target length (0=auto)")
        t_btn    = gr.Button("Generate 🎬", variant="primary")
        t_gif    = gr.Image(label="Result", type="filepath")
        t_inf    = gr.Textbox(label="Info", interactive=False)
        t_btn.click(ui_t2m, [t_prompt, t_len], [t_gif, t_inf])
        gr.Examples([
            ["a person waves their right hand and bows"],
            ["someone jogs forward and jumps"],
            ["a person kicks with the right leg then walks backward"],
            ["a man squats down and stands up quickly"],
        ], t_prompt)
    with gr.Tab("🎬 Motion → Text"):
        m_file = gr.File(label="Upload .npy", file_types=[".npy"])
        m_btn  = gr.Button("Caption 📝", variant="primary")
        m_out  = gr.Textbox(label="Caption", lines=3, interactive=False)
        m_btn.click(ui_m2t, [m_file], [m_out])
    with gr.Tab("🔵 In-Between"):
        ib_file = gr.File(label="Upload .npy", file_types=[".npy"])
        ib_btn  = gr.Button("Complete 🔵", variant="primary")
        with gr.Row():
            ib_in     = gr.Image(label="Original",  type="filepath")
            ib_out_img = gr.Image(label="Completed", type="filepath")
        ib_inf = gr.Textbox(label="Info", interactive=False)
        ib_btn.click(ui_inbetween, [ib_file], [ib_in, ib_out_img, ib_inf])
    with gr.Tab("🟠 Prediction"):
        pd_file = gr.File(label="Upload .npy", file_types=[".npy"])
        pd_btn  = gr.Button("Predict 🟠", variant="primary")
        with gr.Row():
            pd_in  = gr.Image(label="Prefix",    type="filepath")
            pd_out = gr.Image(label="Predicted", type="filepath")
        pd_inf = gr.Textbox(label="Info", interactive=False)
        pd_btn.click(ui_pred, [pd_file], [pd_in, pd_out, pd_inf])

demo.launch()
"""

with open('/content/hf_space/app.py', 'w') as f:
    f.write(app_code)

print('Files created:')
for f in os.listdir('/content/hf_space'):
    print(f'  ✅  {f}')

# Switch to CPU Basic - completely free, no PRO needed
readme = """---
title: MotionGPT Demo
emoji: 🏃
colorFrom: blue
colorTo: purple
sdk: gradio
sdk_version: 3.50.2
app_file: app.py
pinned: false
license: mit
hardware: cpu-basic
---

# 🏃 MotionGPT Demo
Human Motion as a Foreign Language (NeurIPS 2023)

Supports: Text→Motion · Motion→Text · In-Between · Prediction
"""

with open('/content/hf_space/README.md', 'w') as f:
    f.write(readme)

from huggingface_hub import HfApi
api = HfApi()

# Force update by adding a small change
api.upload_file(
    path_or_fileobj='/content/hf_space/README.md',
    path_in_repo='README.md',
    repo_id='GopiBharath/Motion_GPT3',
    repo_type='space',
    commit_message='Switch to cpu-basic hardware'
)
print('✅  Switched to CPU Basic — free, no subscription needed')
print('Generation will take ~5-10s per motion (vs 0.3s on GPU)')
print('Space URL: https://huggingface.co/spaces/GopiBharath/Motion_GPT3')

requirements = """torch
torchvision
torchaudio
--extra-index-url https://download.pytorch.org/whl/cpu

pytorch-lightning
torchmetrics
omegaconf
transformers
tokenizers
einops
rich
tqdm
scipy
numpy
matplotlib
moviepy==1.0.3
imageio
imageio-ffmpeg
gradio==4.44.0
huggingface_hub>=0.25.0
opencv-python
librosa
spacy>=3.8.0
ftfy
more-itertools
natsort
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("✅ requirements.txt updated with opencv-python")

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
    commit_message="Add opencv-python (cv2) to fix import error"
)

from huggingface_hub import list_repo_files

files = list_repo_files("OpenMotionLab/motiongpt3")
print(files)

requirements = """torch
torchvision
torchaudio
--extra-index-url https://download.pytorch.org/whl/cpu

pytorch-lightning
torchmetrics
omegaconf
transformers
tokenizers
einops
rich
tqdm
scipy
numpy
matplotlib
moviepy==1.0.3
imageio
imageio-ffmpeg
gradio==4.44.0
huggingface_hub>=0.25.0

opencv-python
librosa
spacy>=3.8.0
ftfy
more-itertools
natsort

# Force upgrade after install
huggingface_hub>=0.25.0
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("requirements.txt updated")

import gradio as gr

# WORKAROUND for HfFolder error in old huggingface_hub
import huggingface_hub
if not hasattr(huggingface_hub, 'HfFolder'):
    class DummyHfFolder:
        @staticmethod
        def get_token():
            return None
    huggingface_hub.HfFolder = DummyHfFolder
    print("✅ Applied HfFolder workaround")

# === CRITICAL WORKAROUND for Gradio + huggingface_hub compatibility ===
import huggingface_hub
if not hasattr(huggingface_hub, 'HfFolder'):
    class DummyHfFolder:
        @staticmethod
        def get_token():
            return None
    huggingface_hub.HfFolder = DummyHfFolder
    print("✅ Applied HfFolder dummy workaround for Gradio")

reqs = """torch>=2.5.0
pytorch-lightning>=2.2.5
transformers>=4.36.0
tokenizers>=0.15.0
omegaconf
einops
rich
tqdm
scipy
moviepy==1.0.3
imageio
imageio-ffmpeg
matplotlib
bert-score
spacy
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.7.1/en_core_web_sm-3.7.1-py3-none-any.whl
gdown
"""

with open('/content/hf_space/requirements.txt', 'w') as f:
    f.write(reqs)

# Also update README to use latest gradio
readme = """---
title: MotionGPT Demo
emoji: 🏃
colorFrom: blue
colorTo: purple
sdk: gradio
sdk_version: 4.44.0
app_file: app.py
pinned: false
license: mit
hardware: cpu-basic
---

# 🏃 MotionGPT Demo
Human Motion as a Foreign Language (NeurIPS 2023)
Supports: Text→Motion · Motion→Text · In-Between · Prediction
"""

with open('/content/hf_space/README.md', 'w') as f:
    f.write(readme)

# Update app.py to use gradio 4.x syntax
# In gradio 4.x, type='filepath' still works but launch() is slightly different
app_code = open('/content/hf_space/app.py').read()
app_code = app_code.replace('demo.launch()', 'demo.launch(server_name="0.0.0.0")')
with open('/content/hf_space/app.py', 'w') as f:
    f.write(app_code)

from huggingface_hub import HfApi
api = HfApi()
REPO_ID = 'GopiBharath/Motion_GPT3'

for fname in ['requirements.txt', 'README.md', 'app.py']:
    api.upload_file(
        path_or_fileobj=f'/content/hf_space/{fname}',
        path_in_repo=fname,
        repo_id=REPO_ID,
        repo_type='space',
        commit_message=f'Fix torch version and gradio version'
    )
    print(f'✅  {fname} uploaded')

print('\n🚀  Space rebuilding — check logs in 2 min')
print(f'https://huggingface.co/spaces/{REPO_ID}')

# To update requirements.txt, run this in a cell:
with open('requirements.txt', 'r') as f:
    content = f.read()

# Replace the spacy line
content = content.replace('spacy', 'spacy>=3.8.0')  # adjust as needed

with open('requirements.txt', 'w') as f:
    f.write(content)

print(content)  # verify it looks right

# Write the requirements.txt
requirements = """tensorboard
pytorch_lightning
torchmetrics
omegaconf
shortuuid
chumpy
transformers
diffusers
einops
wandb
rich
matplotlib

# for visualization
smplx==0.1.28
trimesh==3.9.24
joblib==1.2.0
h5py
scikit-image
spacy>=3.8.0
ftfy
more-itertools
natsort
pyrender
moviepy
librosa
triangle==20220202
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("requirements.txt written successfully")

from huggingface_hub import HfApi

api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
)
print("Uploaded!")

requirements = """tensorboard
pytorch_lightning
torchmetrics
omegaconf
shortuuid
git+https://github.com/mattloper/chumpy.git
transformers
diffusers
einops
wandb
rich
matplotlib

# for visualization
smplx==0.1.28
trimesh==3.9.24
joblib==1.2.0
h5py
scikit-image
spacy>=3.8.0
ftfy
more-itertools
natsort
pyrender
moviepy
librosa
triangle==20220202
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
)
print("Done!")

requirements = """tensorboard
pytorch_lightning
torchmetrics
omegaconf
shortuuid
numpy
scipy
opencv-python
transformers
diffusers
einops
wandb
rich
matplotlib

# for visualization
smplx==0.1.28
trimesh==3.9.24
joblib==1.2.0
h5py
scikit-image
spacy>=3.8.0
ftfy
more-itertools
natsort
pyrender
moviepy
librosa
triangle==20220202
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
)
print("Done!")

requirements = """tensorboard
pytorch_lightning
torchmetrics
omegaconf
shortuuid
numpy
scipy
opencv-python
transformers
diffusers
einops
wandb
rich
matplotlib

# for visualization
smplx==0.1.28
trimesh==3.9.24
joblib==1.2.0
h5py
scikit-image
spacy>=3.8.0
ftfy
more-itertools
natsort
pyrender
moviepy
librosa
triangle==20250106
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
)
print("Done!")

requirements = """tensorboard
pytorch_lightning
torchmetrics
omegaconf
shortuuid
numpy
scipy
opencv-python
transformers
diffusers
einops
wandb
rich
matplotlib
huggingface_hub==0.23.4

# for visualization
smplx==0.1.28
trimesh==3.9.24
joblib==1.2.0
h5py
scikit-image
spacy>=3.8.0
ftfy
more-itertools
natsort
pyrender
moviepy
librosa
triangle==20250106
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
)
print("Done!")

import subprocess, os, sys

# Clone official MotionGPT repo if not present
if not os.path.exists("/home/user/app/MotionGPT"):
    print("Cloning MotionGPT source from GitHub...")
    subprocess.run([
        "git", "clone", "--depth=1",
        "https://github.com/OpenMotionLab/MotionGPT.git",
        "/home/user/app/MotionGPT"
    ], check=True)

# Set paths
sys.path.insert(0, "/home/user/app/MotionGPT")
os.chdir("/home/user/app/MotionGPT")

# Rest of your imports and code...

!git add .
!git commit -m "deploy app"
!git push

!git config --global user.email "gmakkena@charlotte.edu"
!git config --global user.name "GopiBharath"

from huggingface_hub import notebook_login
notebook_login()

!git remote set-url origin https://YOUR_USERNAME@huggingface.co/spaces/YOUR_USERNAME/YOUR_SPACE

!git add .
!git commit -m "deploy app"
!git push

!git remote set-url origin https://YOUR_USERNAME:YOUR_HF_TOKEN@huggingface.co/spaces/YOUR_USERNAME/YOUR_SPACE

!git push

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="app.py",
    path_in_repo="app.py",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
    commit_message="Added git clone + checkpoint download at top"
)

requirements = """torch
torchvision
torchaudio
--extra-index-url https://download.pytorch.org/whl/cpu

pytorch-lightning
torchmetrics
omegaconf
transformers
tokenizers
einops
rich
tqdm
scipy
numpy
matplotlib
moviepy==1.0.3
imageio
imageio-ffmpeg
gradio==4.44.0
huggingface_hub
librosa
spacy>=3.8.0
ftfy
more-itertools
natsort
pyrender
scikit-image
git+https://github.com/mattloper/chumpy.git
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("requirements.txt updated")

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
    commit_message="Add moviepy and other missing dependencies"
)

requirements = """torch
torchvision
torchaudio
--extra-index-url https://download.pytorch.org/whl/cpu

pytorch-lightning
torchmetrics
omegaconf
transformers
tokenizers
einops
rich
tqdm
scipy
numpy
matplotlib
moviepy==1.0.3
imageio
imageio-ffmpeg
gradio==4.44.0
huggingface_hub
librosa
spacy>=3.8.0
ftfy
more-itertools
natsort
pyrender
scikit-image

# Removed chumpy to fix build
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("✅ requirements.txt updated (chumpy removed)")

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
    commit_message="Remove chumpy to fix build error"
)

requirements = """torch
torchvision
torchaudio
--extra-index-url https://download.pytorch.org/whl/cpu

pytorch-lightning
torchmetrics
omegaconf
transformers
tokenizers
einops
rich
tqdm
scipy
numpy
matplotlib
moviepy==1.0.3
imageio
imageio-ffmpeg
gradio==4.44.0
huggingface_hub>=0.25.0
librosa
spacy>=3.8.0
ftfy
more-itertools
natsort
pyrender
scikit-image
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("✅ requirements.txt updated with compatible huggingface_hub")

requirements = """torch
torchvision
torchaudio
--extra-index-url https://download.pytorch.org/whl/cpu

pytorch-lightning
torchmetrics
omegaconf
transformers
tokenizers
einops
rich
tqdm
scipy
numpy
matplotlib
moviepy==1.0.3
imageio
imageio-ffmpeg
gradio==4.44.0
huggingface_hub>=0.25.0,<0.26.0   # Explicit range
librosa
spacy>=3.8.0
ftfy
more-itertools
natsort
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("✅ Updated requirements.txt with compatible huggingface_hub")

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
    commit_message="Force compatible huggingface_hub version"
)

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
    commit_message="Fix huggingface_hub version conflict with Gradio"
)

requirements = """torch
torchvision
torchaudio
--extra-index-url https://download.pytorch.org/whl/cpu

pytorch-lightning
torchmetrics
omegaconf
transformers
tokenizers
einops
rich
tqdm
scipy
numpy
matplotlib
moviepy==1.0.3
imageio
imageio-ffmpeg
gradio==4.44.0
huggingface_hub>=0.25.0  # Force newer version
librosa
spacy>=3.8.0
ftfy
more-itertools
natsort
pyrender
scikit-image
"""

with open('requirements.txt', 'w') as f:
    f.write(requirements)

print("requirements.txt updated with explicit huggingface_hub>=0.25.0")

from huggingface_hub import HfApi
api = HfApi()
api.upload_file(
    path_or_fileobj="requirements.txt",
    path_in_repo="requirements.txt",
    repo_id="GopiBharath/Motion_GPT3",
    repo_type="space",
    commit_message="Force huggingface_hub>=0.25.0 to fix HfFolder import error"
)

import shutil
from google.colab import files

zip_path = '/content/motiongpt_results'
shutil.make_archive(zip_path, 'zip', '/content/MotionGPT/results')
print(f'Archive ready: {zip_path}.zip')
files.download(f'{zip_path}.zip')